### ISSUE TITLE
can't get it to work for building wine-tkg

### ISSUE THREAD

**Issue by aufkrawall** [Frogging-Family/mostlyportable-gcc#5]
Hello,
certainly no bug, just me being blind and clueless: Could you please drop me a hint how to specify the path for mingw-mostlyportable when building wine-tkg? The script always tells me that mingw-w64-gcc was missing, despite of my attempts to set the variables like described in the readme.
E.g. I did
`customcc="/~/mostlyportable-gcc/mingw-mostlyportable-10.1.1-releases-gcc.10.1.0.r225.g63c00a0c654" PATH=${customcc}/bin:${customcc}/lib:${customcc}/include:${PATH} makepkg`
Thanks!

**Comment by ronoverdrive** [comment]
Edit your customization.cfg file. There's a line there for your custom gcc and you can setup all your build options ahead of time in that file as well as applying any community patches you may want/need.

**Comment by aufkrawall** [comment]
It seems it has disappeared due to some refactoring?
https://github.com/Frogging-Family/wine-tkg-git/blob/master/wine-tkg-git/customization.cfg
(Or should I go see a doctor?)

**Comment by Tk-Glitch** [comment]
Yeah for all explicitly supported tools, you'll want to use the .cfg way. That specific setting has been moved to https://github.com/Frogging-Family/wine-tkg-git/blob/master/wine-tkg-git/wine-tkg-profiles/advanced-customization.cfg (and it wasn't supposed to stay that way for too long but my plans were slowed down by external factors).
You're encouraged to use an external config file which centralizes all options and will survive repo updates nonetheless, which you can find a base for here: https://github.com/Frogging-Family/wine-tkg-git/blob/master/wine-tkg-git/wine-tkg-profiles/sample-external-config.cfg

**Comment by ronoverdrive** [comment]
sorry forgot they moved it to wine-tkg-git/wine-tkg-profiles/advanced-customization.cfg

**Comment by aufkrawall** [comment]
Thank you, it building worked flawlessly that way!

**Comment by Tk-Glitch** [comment]
Great news! :)
